const NATIONALITY = [
    { key: 'usa', text: 'United States', value: 'United States' },
    { key: 'canada', text: 'Canada', value: 'Canada' },
    { key: 'uk', text: 'United Kingdom', value: 'United Kingdom' },
    { key: 'australia', text: 'Australia', value: 'Australia' },
    { key: 'ethopia', text: 'Ethopia', value: 'Ethopia' },
    { key: 'france', text: 'France', value: 'France' },
    { key: 'italy', text: 'Italy', value: 'Italy' },
    { key: 'spain', text: 'Spain', value: 'Spain' },
    { key: 'netherlands', text: 'Netherlands', value: 'Netherlands' },
    { key: 'belgium', text: 'Belgium', value: 'Belgium' },
    { key: 'nigeria', text: 'Nigeria', value: 'Nigeria' },
    { key: 'kenya', text: 'Kenya', value: 'Kenya' },
    { key: 'sweden', text: 'Sweden', value: 'Sweden' },
    { key: 'togo', text: 'Togo', value: 'Togo' },
    { key: 'denmark', text: 'Denmark', value: 'Denmark' },
    { key: 'mali', text: 'Mali', value: 'Mali' },
    { key: 'ireland', text: 'Ireland', value: 'Ireland' },
    { key: 'ghana', text: 'Ghana', value: 'ghana' },
    { key: 'portugal', text: 'Portugal', value: 'portugal' },
    { key: 'greece', text: 'Greece', value: 'greece' },
    { key: 'poland', text: 'Poland', value: 'poland' },
    { key: 'austria', text: 'Austria', value: 'austria' },
    { key: 'hungary', text: 'Hungary', value: 'hungary' },
    { key: 'rwanda', text: 'Rwanda', value: 'rwanda' },
    { key: 'russia', text: 'Russia', value: 'russia' },
    { key: 'china', text: 'China', value: 'china' },
    { key: 'japan', text: 'Japan', value: 'japan' },
    { key: 'southkorea', text: 'South Korea', value: 'south Korea' },
    { key: 'india', text: 'India', value: 'india' },
    { key: 'brazil', text: 'Brazil', value: 'brazil' },
    { key: 'mexico', text: 'Mexico', value: 'mexico' },
    { key: 'argentina', text: 'Argentina', value: 'argentina' },
    { key: 'southafrica', text: 'South Africa', value: 'south Africa' },
    { key: 'egypt', text: 'Egypt', value: 'egypt' },
  
    // Add more countries as needed
  ];
  
  export default NATIONALITY;
  